-- WORD LISTS (Hybrid: Relational Metadata + JSON Content)
CREATE TABLE word_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  name TEXT NOT NULL,

  words JSONB NOT NULL DEFAULT '[]'::jsonb,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE word_lists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Manage own word lists"
ON word_lists FOR ALL
USING (auth.uid() = user_id);

-- QUIZZES (Hybrid: Relational Metadata + JSON Content)
CREATE TABLE quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,

  -- Relational Metadata for filtering/searching
  -- Example: '{"url": "...", "title": "...", "type": "article"}'
  context JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT DEFAULT 'ready', -- 'generating', 'ready', 'error'

  -- The Quiz Content (JSONB)
  -- Example: [{"question": "...", "answer": "...", "options": [...]}]
  content JSONB DEFAULT NULL,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Manage own quizzes"
ON quizzes FOR ALL
USING (auth.uid() = user_id);

-- Keeps track of which word lists were used to generate a quiz
CREATE TABLE quiz_word_lists (
  quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE,
  word_list_id BIGINT REFERENCES word_lists(id) ON DELETE CASCADE,
  PRIMARY KEY (quiz_id, word_list_id)
);

ALTER TABLE quiz_word_lists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Manage own quiz links"
ON quiz_word_lists FOR ALL
USING (
  EXISTS (SELECT 1 FROM quizzes WHERE id = quiz_word_lists.quiz_id AND user_id = auth.uid())
);

-- ATTEMPTS / HISTORY
CREATE TABLE quiz_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE NOT NULL,

  -- Relational Score for Analytics
  score INTEGER NOT NULL DEFAULT 0,
  max_score INTEGER NOT NULL DEFAULT 0,

  -- Detailed Review Data
  responses JSONB DEFAULT '{}'::jsonb,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE quiz_attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Manage own attempts"
ON quiz_attempts FOR ALL
USING (auth.uid() = user_id);

-- 5. LANGGRAPH STATE
CREATE TABLE checkpoints (
    thread_id TEXT NOT NULL,
    checkpoint_ns TEXT NOT NULL DEFAULT '',
    checkpoint_id TEXT NOT NULL,
    parent_checkpoint_id TEXT,
    type TEXT,
    checkpoint JSONB NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
);

CREATE TABLE checkpoint_blobs (
    thread_id TEXT NOT NULL,
    checkpoint_ns TEXT NOT NULL DEFAULT '',
    channel TEXT NOT NULL,
    version TEXT NOT NULL,
    type TEXT NOT NULL,
    blob BYTEA,
    PRIMARY KEY (thread_id, checkpoint_ns, channel, version)
);

CREATE TABLE checkpoint_writes (
    thread_id TEXT NOT NULL,
    checkpoint_ns TEXT NOT NULL DEFAULT '',
    checkpoint_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    idx INTEGER NOT NULL,
    channel TEXT NOT NULL,
    type TEXT,
    blob BYTEA,
    PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)
);

-- Allow backend (Service Role) full access, or configure RLS if client-side resumption is needed.
ALTER TABLE checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint_blobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint_writes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users access own threads" ON checkpoints FOR ALL USING (thread_id LIKE auth.uid()::text || '%');
CREATE POLICY "Users access own threads blobs" ON checkpoint_blobs FOR ALL USING (thread_id LIKE auth.uid()::text || '%');
CREATE POLICY "Users access own threads writes" ON checkpoint_writes FOR ALL USING (thread_id LIKE auth.uid()::text || '%');
